INSERT INTO songs(SINGER, SONG, GENRE, YEAR) VALUES 
    ('Woody Guthrie', 'This Land is Your Land', 'Folk', 1940 ),
    ('Leonard Cohen', 'Suzanne','Folk', 1967 ),
    ('Joni Mitchell', 'Both Sides Now', 'Folk', 1966 ),
    ('Bob Dylan', 'Don’t Think Twice', 'Folk', 1963 ),
    ('John Prine', 'Hello In There', 'Folk', 1971 ),
    ('Elizabeth Cotton', 'Freight Train', 'Folk', 1957 ),
    ('Bob Dylan', 'Like a Rolling Stone', 'Folk', 1965 ),
    ('John Prine', 'Paradise', 'Folk', 1971 ),
    ('Phil Ochs', 'Changes', 'Folk', 1966 ),
    ('Ralph McTell', 'Streets of London', 'Folk', 1969 ),
    ('Malvina Reynolds', 'Little Boxes', 'Folk', 1962 ),
    ('Tom Rush', 'No Regrets', 'Folk', 1968 ),
    ('Donovan', 'Catch The Wind', 'Folk', 1965 ),
    ('Bob Dylan', 'Tangled Up In Blue', 'Folk', 1975 ),
    ('Bob Dylan', 'Masters of War', 'Folk', 1963 ),
    ('Carter Family', 'Wildwood Flower', 'Folk', 1928 ),
    ('Phil Ochs', 'The Crucifixion', 'Folk', 1967 ),
    ('John Prine', 'Angel from Montgomery', 'Folk', 1971 ),
    ('Ewan MacColl', 'Dirty Old Town', 'Folk', 1949 ),
    ('Leonard Cohen', 'Hallelujah', 'Folk', 1984 ),
    ('Mamie Smith', 'Crazy Blues', 'Blues', 1920 ),
    ('Pine Top Smith', 'Pine Top Boogie', 'Blues', 1928 ),
    ('Elmore James', 'Dust My Broom', 'Blues', 2012 ),
    ('John Lee Hooker', 'Boogie Chillun', 'Blues', 1948 ),
    ('Muddy Waters', 'Mannish Boy', 'Blues', 1955 ),
    ('T-Bone Walker', 'Stormy Monday', 'Blues', 1947 ),
    ('Robert Johnson', 'Hellhound On My Trail', 'Blues', 1961 ),
    ('Willie Dixon', 'Spoonful', 'Blues', 1960 ),
    ('Roosevelt Sykes', 'Forty Four Blues', 'Blues', 1929 ),
    ('Little Walter', 'Juke', 'Blues', 1952 ),
    ('Willie Dixon', 'Back Door Man', 'Blues', 1967 ),
    ('Freddie King', 'Hideaway', 'Blues', 1961 ),
    ('Eddie Boyd', 'Five Long Years', 'Blues', 1949 ),
    ('Jimi Hendrix', 'Red House', 'Blues', 1967 ),
    ('Robert Johnson', 'Cross Road Blues', 'Blues', 1937 ),
    ('Robert Nighthawk', 'Sweet Black Angel', 'Blues', 2007 ),
    ('John Lee Hooker', 'Boom Boom', 'Blues', 1962 ),
    ('Charley Patton', 'Pony Blues', 'Blues', 1929 ),
    ('Dave Brubeck', 'Take Five', 'Juzz', 1959 ),
    ('Miles Davis', 'So What', 'Juzz', 1959 ),
    ('Duke Ellington', 'Take The A Train', 'Juzz', 1939 ),
    ('Thelonious Monk', 'Round Midnight', 'Juzz', 1944 ),
    ('John Coltrane', 'My Favorite Things', 'Juzz', 1961 ),
    ('Miles Davis', 'All Blues', 'Juzz', 1959 ),
    ('Weather Report', 'Birdland', 'Juzz', 1977 ),
    ('Benny Goodman', 'Sing, Sing, Sing', 'Juzz', 1937 ),
    ('Billie Holiday', 'Strange Fruit', 'Juzz', 1939 ),
    ('Dizzy Gillespie', 'A Night in Tunisia', 'Juzz', 1942 ),
    ('John Coltrane', 'Giant Steps', 'Juzz', 1960 ),
    ('Oliver Nelson', 'Stolen Moments', 'Juzz', 1961 ),
    ('Louis Armstrong', 'West End Blues', 'Juzz', 1928 ),
    ('Coleman Hawkins', 'Body And Soul', 'Juzz', 1956 ),
    ('Chick Corea', 'Spain', 'Juzz', 1973 ),
    ('John Coltrane', 'Naima', 'Juzz', 1959 ),
    ('Sonny Rollins', 'St. Thomas', 'Juzz', 1956 ),
    ('John Coltrane', 'Blue Train', 'Juzz', 1958 ),
    ('Miles Davis', 'Freddie Freeloader', 'Juzz', 1959 ),
    ('Ella Fitzgerald', 'Summertime', 'Juzz', 1958 ),
    ('Jimi Hendrix', 'Purple Haze', 'Rock', 1967 ),
    ('The Rolling Stones', 'Start Me Up', 'Rock', 1981 ),
    ('Led Zeppelin', 'Whole Lotta Love', 'Rock', 1969 ),
    ('Aerosmith', 'Walk This Way', 'Rock', 1975 ),
    ('The Who', 'Baba O’Riley', 'Rock', 1971 ),
    ('Pink Floyd', 'Comfortably Numb', 'Rock', 1979 ),
    ('Black Sabbath', 'Iron Man', 'Rock', 1970 ),
    ('Deep Purple', 'Smoke on the Water', 'Rock', 1971 ),
    ('Golden Earring', 'Radar Love', 'Rock', 1973 ),
    ('Stevie Nicks', 'Edge of Seventeen', 'Rock', 1981 ),
    ('Van Morrison', 'Brown Eyed Girl', 'Rock', 1967 ),
    ('Lynyrd Skynyrd', 'Sweet Home Alabama', 'Rock', 1974 ),
    ('The Cars', 'Just What I Needed', 'Rock', 1978 ),
    ('Jethro Tull', 'Locomotive Breath', 'Rock', 1971 ),
    ('Nirvana', 'All Apologies', 'Lyrics', 1993 ),
    ('Joy Division', 'Love Will Tear Us Apart', 'Lyrics', 1980 ),
    ('Laura Marling', 'Ghosts', 'Lyrics', 2008 ),
    ('Leonard Cohen', 'So Long, Marianne', 'Lyrics', 1967 ),
    ('Nick Cave', 'Into My Arms', 'Lyrics', 1997 ),
    ('Sisters Of Mercy', 'This Corrosion', 'Lyrics', 1987 ),
    ('Bruce Springsteen', 'I’m On Fire', 'Lyrics', 1984 ),
    ('Tori Amos', 'Father Lucifer', 'Lyrics', 1996 ),
    ('Kendrick Lamar', 'Swimming Pool', 'Lyrics', 2012 ),
    ('Rolling Stones', 'Gimme Shelter', 'Lyrics', 1969 ),
    ('David Bowie', 'Station to Station', 'Lyrics', 1976 ),
    ('Oasis', 'Supersonic', 'Lyrics', 1994 ),
    ('Underworld', 'Born Slippy', 'Lyrics', 1996 ),
    ('Fleetwood Mac', 'Landslide', 'Lyrics', 1975 ),
    ('Paul Simon', 'Graceland', 'Lyrics', 1986 ),
    ('Patti Smith', 'Gloria', 'Lyrics', 1975 ),
    ('Eagles', 'Hotel California', 'Lyrics', 1977 ),
    ('Nina Simone', 'Four Women', 'Lyrics', 1966 ),
    ('St Vincent', 'Digital Witness', 'Lyrics', 2014 ),
    ('Rufus Wainwright', 'Dinner at Eight', 'Lyrics', 2003 ),
    ('Abba', 'The Winner Takes It All', 'Lyrics', 1980 ),
    ('The Stone Roses', 'I Wanna Be Adored', 'Lyrics', 1989 )
